### ISSUE TITLE
Getting all versions allows for duplicate versions.

### ISSUE THREAD

**Issue by Maxine-van-der-Smissen** [Mastermindzh/BetterVersioning.net#5]
When the versions are parsed, duplicates are not removed.
This leads to duplicate versions being registered on the controller and actions, and would result in issues when checking for duplicate actions inside the `BetterVersioningConventionBuilder` if it checked versions.

The following code produces duplicated versions for `1.0`, `2.2` and `3.0`.

```csharp
// set up versions
var versions = new[] {
  new BetterVersion(1),
  new BetterVersion(1),
  new BetterVersion(2, new ushort[]{1,2,2}),
  new BetterVersion(3, new ushort[]{0,1})
};
```

An `ArgumentException` should be thrown when duplicates are found, except for the implied version `x.0`, which should only be added once.

**Comment by Mastermindzh** [comment]
Merged, packaged, published:
https://ci.mastermindzh.tech/Mastermindzh/BetterVersioning.net/16/1/6

Yay!
